version: '3.8'

services:
  app:
    container_name: tube2link
    build:
      context: .
      target: ${TARGET:-runner} # Use 'development' or 'runner' based on environment
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/app:ro
      - /app/node_modules
      - /app/.next
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
